//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelLob.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class FullInfoEmployee
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Gender { get; set; }
        public string PassportCode { get; set; }
        public string PassportSeries { get; set; }
        public System.DateTime DateOfBirthday { get; set; }
        public string NameCategory { get; set; }
        public decimal Salary { get; set; }
        public decimal Coefficient { get; set; }
        public string NamePost { get; set; }
    }
}
