//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelLob.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderRoom
    {
        public int IdOrder { get; set; }
        public int IdRoom { get; set; }
        public int IdOrderRoom { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Room Room { get; set; }
    }
}
